routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use Illuminate\Support\Facades\Auth;
use PHPUnit\TextUI\XmlConfiguration\Group;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();


Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');




Route::middleware(['auth', 'admin'])->group(function () {

    Route::get('blogconfirm/{id}',[App\Http\Controllers\AdminController::class,'confirm'])->name('blog.confirm');
    Route::get('/admin', [App\Http\Controllers\AdminController::class,'index']);
    Route::get('adminshow', [App\Http\Controllers\AdminController::class,'showblogs'])->name('admin.show');
});

Route::POST('/img',[App\Http\Controllers\ImgController::class,'index'])->name('img');



Route::resource('/blog', App\Http\Controllers\BlogController::class);

Route::get('/create',[App\Http\Controllers\BlogController::class,'store'])->middleware('auth')->name('create');


Route::post('commentaire',[App\Http\Controllers\CommentController::class,'commentaire'])->name('commentaire');

resources/views/admin.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                 <h1>hello admin!</h1>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/adminshow.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row">

        <table class="table table-hover">

            <thead>
              <tr>
                <th scope="col">id</th>
                <th scope="col">title</th>
                <th scope="col">article</th>
                <th scope="col">user_id</th>
                <th scope="col">confirmation</th>
                <th>confirmé</th>
              </tr>
            </thead>
            <tbody>
                @foreach ($blog as $item )
              <tr>
                <td>{{ $item->id}}</td>
                <td>{{ $item->title}}</td>
                <td>{{ $item->article}}</td>
               <td>{{ $item->user_id}}</td>
               <td>{{ $item->confirmation}}</td>
               <td> <a href="{{  route('blog.confirm',['id' => $item->id])}}" class="btn btn-success">Confirm</a></td>
               <td><a href="{{ route('blog.edit',['blog' => $item->id ])}}" class="btn btn-danger"> delete</a></td>
              </tr>
              @endforeach
            </tbody>
          </table>

    </div>
</div>

@endsection

resources/views/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
   <div class="row">
     <!--{{ route('blog.create')}}-->
    <form action="{{ route('img')}}" method="POST" enctype="multipart/form-data">
      @csrf
      @method('POST')
      <div class="form-group">
        <label for="title">title</label>
        <input type="text" class="form-control" id="title" name="title" aria-describedby="emailHelp" placeholder="Enter title">
      </div>


        <div class="form-group">
          <label for="article">Example textarea</label>
          <textarea class="form-control" name="article" id="article" rows="3"></textarea>
        </div>

        <div class="form-group">
          <label for="image">image</label>
          <input type="file" class="form-control" id="user_id" name="image" aria-describedby="emailHelp" placeholder="Enter title">
        </div>





      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
   </div>
 </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img height="500px;" src="https://chacc.co.uk/wp-content/uploads/2021/06/Effective-Bookkeeping-For-Business-Growth.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img height="500px;" src="https://www.fireflynetworks.co.in/blog/wp-content/uploads/2019/05/blog-1.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img height="500px;" src="https://2.bp.blogspot.com/-GwpxqJ2FSXE/WCq3JftbKHI/AAAAAAAAVSo/iSx3R1Gh_nQqxzk7OBoGHcbA9xUbz39TACLcB/s1600/IMG_9975.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<br>
<div class="col-lg-9">
          <div class="row">
            @foreach ($blog as $item)

            <div class="card col-lg-4 col-sm-12"  >

              <img src="{{ asset('/storage/images/'.$item->image) }}" class="card-img-top" alt="...">

              <div class="card-body">
                <h5 class="card-title"> {{$item->title}}</h5>
                <p class="card-text"> {{$item->article}}</p>

                <h3 class="blockquote-footer"> auteur:{{ $item->user_id}}</h3>
                <a href="{{ route('blog.show',['blog' => $item->id ])}}" class="btn btn-primary">Show More </a>

                @if ( Auth::check() && (Auth::user()->id == $item->user_id) )
                   <a href="{{ route('blog.delete',['blog' => $item->id ])}}" class="btn btn-danger">Delete </a>
                @endif




                </div>
                </div>


                @endforeach
          </div>

        </div>

@endsection

resources/views/oneblog.blade.php
@extends('layouts.app')

@section('content')

    <div class="container"  style="margin-top:20px;">
        <div class="row" style="margin-bottom: 20px;">
         @foreach ($blog as $item)
               <div class="card col-lg-12 col-sm-12"  >
                   <img src="{{ asset('/storage/images/'.$item->image) }}" class="card-img-top" alt="...">
                   <div class="card-body">
                   <h1 class="card-title text-center"> {{$item->title}}</h1>
                   <p class="card-text"> {{$item->article}}</p>
                   <h3 class="blockquote"> auteur:{{ $item->user_id}}</h3>


            <div >
                    <a href="{{ route('blog.show',['blog' => $item->id ])}}" class="btn btn-primary">Show More</a>

                    <!-- supemmer le blog --------------------->
                    @if ( Auth::check() &&(Auth::user()->id === $item->user_id) ||  Auth::check() && (Auth::user()->role == 'admin') )
                    <a href="{{ route('blog.edit',['blog' => $item->id ])}}" class="btn btn-danger">Delete </a>
                    @endif
                    <br> <br> <br>
         </div>
                 <!-- -------------------------------------------- --------------------->


                   </div>

          </div>


        </div>









        <div>


            <h1 style="color: blueviolet;">
                commentaires
            </h1>

            <form action="{{ route('commentaire')}}" method="POST">
                @csrf
                @method('POST')
                <div class="form-group ">
                    <label for="exampleFormControlInput1">commentaire </label>
                    <div class="row">
                        <textarea class="form-control" name="comments" placeholder="Leave a comments"></textarea>
                        <!-- <input type="text" class="form-control col-lg-6" name="comments" id="" placeholder="commentaires"> -->
                        <input type="hidden" name="id" value="{{ $item->id}}">
                        <input type="submit" class="btn btn-success">
                    </div>

                  </div>

            </form>
            @endforeach
        </div>
    </div>








        <div class="container">
            @foreach ($commentaire as $cm )
            <div style="background-color: rgb(255, 255, 255,0.5);margin-top: 20px;box-shadow: 2px 2px 10px  black; padding:10px" class="col-lg-6">


                 <h5> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                  </svg>  {{$cm->user_name}} </h5>


                  <h3> {{$cm->commentarie}}</h3>

                  <p class="blockquote-footer">{{$cm->created_at}}</p>
            </div>
            @endforeach
        </div>

@endsection